### ISSUE TITLE
Build failed after upgrade hmac-sha256 from 1.0.0 to 1.1.0

### ISSUE THREAD

**Issue by Xuanwo** [jedisct1/rust-jwt-simple#47]
```rust
error[E0277]: the trait bound `hmac_sha512::sha384::Hash: FixedOutputDirty` is not satisfied
    --> /home/xuanwo/.cargo/registry/src/github.com-1ecc6299db9ec823/jwt-simple-0.10.7/src/algorithms/rsa.rs:1037:9
     |
1037 |         rsa::PaddingScheme::new_pss::<hmac_sha384::Hash, _>(rand::thread_rng())
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `FixedOutputDirty` is not implemented for `hmac_sha512::sha384::Hash`
     |
     = note: required because of the requirements on the impl of `FixedOutput` for `hmac_sha512::sha384::Hash`
     = note: required because of the requirements on the impl of `Digest` for `hmac_sha512::sha384::Hash`
note: required by a bound in `PaddingScheme::new_pss`
    --> /home/xuanwo/.cargo/registry/src/github.com-1ecc6299db9ec823/rsa-0.5.0/src/padding.rs:143:33
     |
143  |     pub fn new_pss<T: 'static + Digest + DynDigest, S: 'static + RngCore>(rng: S) -> Self {
     |                                 ^^^^^^ required by this bound in `PaddingScheme::new_pss`

```

hmac-sha256 seems incompatible with 1.0.0, PTAL.

**Comment by jedisct1** [comment]
The Rust crypto traits keep changing all the time, this is so depressing.

**Comment by tshepang** [comment]
I would only be sad if the changes broke semver promise, and it seems to be the case here. Otherwise, changes here I believe means improved APIs, so I embrace. And I trust.
